# parsers.py
"""
parsers.py
----------
Input Generation and Output Parsing Logic for FASTRAN GUI.

Responsibilities:
1. Input Generator: Converts GUI variables into the strict whitespace-delimited
   text format required by FASTRAN 5.4.
2. Output Parser: Reads .fou files and extracts tabular data for plotting.
3. Legacy Material Support: Parses old XML material files if needed.
"""

import os
import config
import re

# ------------------------------------------------------------------
# 1. INPUT GENERATION
# ------------------------------------------------------------------
def generate_fastran_input(filepath, vars_dict, is_dict=False):
    """
    Generates the main FASTRAN input file based on the rules in config.py.

    Args:
        filepath (str): Absolute path where the input file will be saved.
        vars_dict (dict): The dictionary containing the values.
        is_dict (bool): True if vars_dict is a plain Python dict (Batch mode).
                        False if it contains Tkinter StringVars (GUI mode).

    Returns:
        tuple: (Success (bool), Message (str))
    """
    try:
        # Helper to extract value regardless of source type
        def get_val(key):
            if key not in vars_dict:
                return config.DEFAULT_VALUES.get(key, "0.0")
            val = vars_dict[key]
            return val if is_dict else val.get()

        lines = []
        
        # --- Line 1: Title ---
        lines.append("FASTRAN ANALYSIS GENERATED BY GUI V3.0")

        # --- Line 2: Units & Plotting ---
        # Format: LUNIT IUNIT NPLOT IPLOT
        lunit = get_val('LUNIT')
        iunit = get_val('IUNIT')
        nplot = get_val('NPLOT')
        iplot = get_val('IPLOT')
        lines.append(f"{lunit} {iunit} {nplot} {iplot}")

        # --- Line 3: Geometry & Material ---
        # Format: NTYP MAT_NAME
        # Extract ID from "1: Center Crack" -> "1"
        ntyp_raw = get_val('NTYP')
        ntyp = int(ntyp_raw.split(':')[0]) if ':' in ntyp_raw else int(ntyp_raw)
        mat_name = get_val('MAT')
        lines.append(f"{ntyp} {mat_name}")

        # --- Line 4: Mechanical Properties ---
        # Format: SYIELD SULT E ETA ALP BETAT BETAW
        props = [
            get_val('SYIELD'), get_val('SULT'), get_val('E'), get_val('ETA'),
            get_val('ALP'), get_val('BETAT'), get_val('BETAW')
        ]
        lines.append(" ".join(map(str, props)))

        # --- Line 5: Crack Growth Options ---
        # Format: NTAB KTAB IRATE NGC NEQN
        ntab = get_val('NTAB')
        ktab = get_val('KTAB')
        irate = get_val('IRATE')
        ngc = get_val('NGC')
        neqn = get_val('NEQN')
        lines.append(f"{ntab} {ktab} {irate} {ngc} {neqn}")

        # --- Line 6 & 7: Paris Constants (If NTAB=0) ---
        if int(ntab) == 0:
            # C1-C4
            c_vals1 = [get_val('C1'), get_val('C2'), get_val('C3'), get_val('C4')]
            lines.append(" ".join(map(str, c_vals1)))
            # C5-C7
            c_vals2 = [get_val('C5'), get_val('C6'), get_val('C7')]
            lines.append(" ".join(map(str, c_vals2)))

        # --- SPECIAL INPUTS (The "Trap" Section 14) ---
        # Check config for special requirements for this NTYP
        geom_rules = config.NTYP_DATA.get(ntyp, {})
        special_reqs = geom_rules.get('special', [])
        
        if special_reqs:
            special_vals = []
            for req in special_reqs:
                special_vals.append(get_val(req))
            lines.append(" ".join(map(str, special_vals)))

        # --- Loading Line ---
        # Format: NFOPT SMAX R FW FH INVERT OMIT IOPEN
        nfopt_raw = get_val('NFOPT')
        nfopt = int(nfopt_raw.split(':')[0]) if ':' in nfopt_raw else int(nfopt_raw)
        
        load_vals = [
            nfopt, get_val('SMAX'), get_val('R'), get_val('FW'), get_val('FH'),
            get_val('INVERT'), get_val('OMIT'), get_val('IOPEN')
        ]
        lines.append(" ".join(map(str, load_vals)))

        # --- Spectrum File (Conditional) ---
        # If NFOPT requires a file, some versions expect it on the next line
        nfopt_rule = config.NFOPT_DATA.get(nfopt, {})
        if nfopt_rule.get('requires_spectrum', False):
            # We assume the code handles the file link separately or via stdin,
            # but legacy formats sometimes put the filename here.
            # We check if a 'SPECTRA' value exists and is not default
            spectra = get_val('SPECTRA')
            if spectra and spectra != 'cstamp.txt':
                lines.append(spectra)

        # --- Geometry Dimensions ---
        # Format: CI CF CN W B AN
        dims = [
            get_val('CI'), get_val('CF'), get_val('CN'),
            get_val('W'), get_val('B'), get_val('AN')
        ]
        lines.append(" ".join(map(str, dims)))

        # --- WRITE TO FILE ---
        with open(filepath, 'w') as f:
            f.write("\n".join(lines))
        
        return True, "Input file generated successfully."

    except Exception as e:
        return False, f"Generation Error: {str(e)}"

# ------------------------------------------------------------------
# 2. OUTPUT PARSING (For Post-Processor)
# ------------------------------------------------------------------
def parse_output_table(filepath):
    """
    Reads a .fou output file and extracts numeric data columns.
    Used by the Post-Processor to plot results.

    Returns:
        headers (list): List of column names (e.g. ['CYCLES', 'C-LENGTH'])
        data (dict): Dictionary mapping header name to list of floats.
    """
    data_dict = {}
    headers = []
    
    if not os.path.exists(filepath):
        return [], {}

    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            
        start_parsing = False
        
        for line in lines:
            stripped = line.strip()
            
            # Detect Header Line
            if "CYCLES" in stripped and "C-LENGTH" in stripped and not start_parsing:
                # Normalize headers
                raw_headers = stripped.split()
                # Clean up headers (remove parens like (mm))
                headers = [h.split('(')[0] for h in raw_headers] 
                
                # Initialize lists
                for h in headers:
                    data_dict[h] = []
                
                start_parsing = True
                continue
                
            if start_parsing:
                # Stop conditions
                if "TOTAL CYCLES" in stripped or len(stripped) == 0:
                    if len(data_dict[headers[0]]) > 0:
                        break # Done
                    else:
                        continue # Empty line but maybe more data coming?
                
                # Parse Numbers
                parts = stripped.split()
                
                # Validate line structure
                if len(parts) >= len(headers) and parts[0][0].isdigit():
                    try:
                        # Attempt to parse row
                        row_vals = []
                        for val in parts[:len(headers)]:
                            row_vals.append(float(val))
                        
                        # If successful, add to dict
                        for i, val in enumerate(row_vals):
                            data_dict[headers[i]].append(val)
                    except ValueError:
                        continue # Skip malformed lines

        return headers, data_dict

    except Exception as e:
        print(f"Error parsing {filepath}: {e}")
        return [], {}

# ------------------------------------------------------------------
# 3. LEGACY MATERIAL SUPPORT (Optional)
# ------------------------------------------------------------------
def parse_material_xml(filepath):
    """
    Parses legacy .lkpx or XML material files (NASGRO style).
    This logic is preserved from your original upload for backward compatibility.
    """
    import xml.etree.ElementTree as ET
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
        
        # Extract basic properties if available
        # This is highly dependent on the XML schema used
        name = root.findtext('.//Material/Name', 'Unknown')
        
        # Return a dict structure compatible with our GUI
        # (Simplified implementation)
        return {'MAT': name}
        
    except Exception:
        return None